# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-24 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser_decodertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='decodertype',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='iucnumber',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phonenumber',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
