# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-24 17:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('publishedDate', models.DateTimeField(blank=True, null=True)),
                ('genreImages', models.FileField(null=True, upload_to=b'Series/GenreImage/')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('publishedDate', models.DateTimeField(blank=True, null=True)),
                ('seriesImages', models.FileField(null=True, upload_to=b'Series/SeriesImage/')),
                ('seriesVideo', models.FileField(null=True, upload_to=b'Series/SerieVideo/')),
                ('genres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seriesapp.Genre')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
