# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-25 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seriesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='publishedDate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
