# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-27 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishedDate', models.IntegerField(blank=True, null=True)),
                ('mainActorImages', models.FileField(null=True, upload_to=b'Movie/ActorsImage/')),
                ('secondActorImages', models.FileField(null=True, upload_to=b'Movie/ActorsImage/')),
                ('thirdActorImages', models.FileField(null=True, upload_to=b'Movie/ActorsImage/')),
                ('fourthActorImages', models.FileField(null=True, upload_to=b'Movie/ActorsImage/')),
                ('movies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('publishedDate', models.IntegerField(blank=True, null=True)),
                ('directorImages', models.FileField(null=True, upload_to=b'Movie/DirectorImage/')),
                ('movies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.Movie')),
            ],
        ),
    ]
