# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-27 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_actor_director'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='name',
            new_name='directorName',
        ),
    ]
