# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-27 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_auto_20190227_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
