# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-17 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_actor_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='movies',
        ),
        migrations.RemoveField(
            model_name='director',
            name='movies',
        ),
        migrations.AddField(
            model_name='actor',
            name='actorFour',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actor',
            name='actorOne',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actor',
            name='actorThree',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actor',
            name='actorTwo',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movieapp.Actor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movieapp.Director'),
            preserve_default=False,
        ),
    ]
